# Generated by Django 3.2.5 on 2022-02-19 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('user', models.CharField(choices=[('CHILD', 'Child'), ('PARENT', 'Parent')], max_length=10)),
                ('address', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Address line')),
                ('street', models.CharField(blank=True, max_length=20, null=True, verbose_name='Street')),
                ('city', models.CharField(blank=True, max_length=1024, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='State')),
                ('zip_code', models.IntegerField(blank=True, null=True, verbose_name='ZIP / Postal code')),
                ('parentName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.features')),
            ],
        ),
    ]
