# Generated by Django 3.2.5 on 2022-02-19 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='features',
            old_name='parentName',
            new_name='parentId',
        ),
    ]
